openapi: 3.0.0
info:
  title: MiniBlog API
  version: 1.0.0
  description: API REST para gestionar authors y posts de un miniblog

servers:
  - url: https://proyectom2lunagomez-production.up.railway.app

  tags:
  - name: Authors
    description: Operaciones relacionadas con autores
  - name: Posts
    description: Operaciones relacionadas con publicaciones

paths:
  /api/authors:
    get:
    tags: [Authors]
      summary: Obtener todos los autores
      responses:
        '200':
          description: Lista de autores
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
    post:
    tags: [Authors]
      summary: Crear un nuevo autor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
              properties:
                name:
                  type: string
                email:
                  type: string
                bio:
                  type: string
      responses:
        '201':
          description: Autor creado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
        '400':
          description: Datos inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409': 
          description: Problema (ejemplo. email duplicado)
          content:
            application/json:
              schema:
              $ref: '#/components/schemas/Error'


  /api/authors/{id}:
    get:
    tags: [Authors]
      summary: Obtener autor por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Autor encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
        '400':
          description: ID inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Autor no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags: [Authors]
      summary: Actualizar autor
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
              properties:
                name:
                  type: string
                email:
                  type: string
                bio:
                  type: string
      responses:
        '200':
          description: Autor actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
          '400':
          description: ID inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'      
        '404':
          description: Autor no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
    tags: [Authors]
      summary: Eliminar autor
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Autor eliminado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
         '400':
          description: ID inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'       
        '404':
          description: Autor no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/posts:
    get:
    tags: [Posts]
      summary: Obtener todos los posts
      responses:
        '200':
          description: Lista de posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
    post:
    tags: [Posts]
      summary: Crear un nuevo post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - content
                - author_id
              properties:
                title:
                  type: string
                content:
                  type: string
                author_id:
                  type: integer
                published:
                  type: boolean
      responses:
        '201':
          description: Post creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '400':
          description: Datos inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/posts/{id}:
    get:
    tags: [Posts]
      summary: Obtener post por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Post encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Post no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
    tags: [Posts]
      summary: Actualizar post
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - content
                - author_id
              properties:
                title:
                  type: string
                content:
                  type: string
                author_id:
                  type: integer
                published:
                  type: boolean
      responses:
        '200':
          description: Post actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Post no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
    tags: [Posts]
      summary: Eliminar post
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Post eliminado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  post:
                    $ref: '#/components/schemas/Post'
        '404':
          description: Post no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/posts/author/{authorId}:
    get:
    tags: [Posts]
      summary: Obtener posts por autor
      parameters:
        - in: path
          name: authorId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Lista de posts del autor
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PostWithAuthor'

Author:
  type: object
  properties:
    id:
      type: integer
      example: 1
    name:
      type: string
      example: Gabriel García Márquez
    email:
      type: string
      example: gabriel@email.com
    bio:
      type: string
      example: Escritor colombiano
    created_at:
      type: string
      format: date-time
      example: 2026-03-13T10:00:00.000Z

    Post:
  type: object
  properties:
    id:
      type: integer
      example: 1
    title:
      type: string
      example: Cien años de soledad
    content:
      type: string
      example: Novela de la literaria latinoamericana.
    author_id:
      type: integer
      example: 1
    published:
      type: boolean
      example: true
    created_at:
      type: string
      format: date-time
      example: 2026-03-13T10:00:00.000Z

    PostWithAuthor:
  type: object
  properties:
    id:
      type: integer
      example: 1
    title:
      type: string
      example: Cien años de soledad
    content:
      type: string
      example: Novela literaria latinoamericana.
    author_id:
      type: integer
      example: 1
    published:
      type: boolean
      example: true
    created_at:
      type: string
      format: date-time
      example: 2026-03-13T10:00:00.000Z
    author_name:
      type: string
      example: Gabriel García Márquez
    author_email:
      type: string
      example: gabriel@email.com
    author_bio:
      type: string
      example: Escritor colombiano

    Error:
      type: object
      properties:
        error:
          type: string
          example: Autor no encontrado